config/routes.rb
Meters::Application.routes.draw do
  resources :readings
  root :to => 'readings#new'
  

end

app/models/reading.rb
class Reading < ActiveRecord::Base

  def body=(body)
    parse(body)
    #self.body = nil
  end
  
  def body
  end
  
  private
  
  def parse(body)
    self.gas = '12345'
    self.electric = '67890'
    self.email = 'd@sofer.com'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @readings }
    end
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/new
  # GET /readings/new.json
  def new
    @reading = Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @reading = Reading.find(params[:id])
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(params[:reading])

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render json: @reading, status: :created, location: @reading }
      else
        format.html { render action: "new" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.json
  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to readings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meters</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gas %><br />
    <%= f.number_field :gas %>
  </div>
  <div class="field">
    <%= f.label :electric %><br />
    <%= f.number_field :electric %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<h1>Listing readings</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Gas</th>
    <th>Electric</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @readings.each do |reading| %>
  <tr>
    <td><%= reading.email %></td>
    <td><%= reading.gas %></td>
    <td><%= reading.electric %></td>
    <td><%= link_to 'Show', reading %></td>
    <td><%= link_to 'Edit', edit_reading_path(reading) %></td>
    <td><%= link_to 'Destroy', reading, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reading', new_reading_path %>

app/views/readings/new.html.erb
<h1>New reading</h1>

<%= render 'form' %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @reading.email %>
</p>

<p>
  <b>Gas:</b>
  <%= @reading.gas %>
</p>

<p>
  <b>Electric:</b>
  <%= @reading.electric %>
</p>


<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>